FROM python:3.11-slim

WORKDIR /usr/src/app

COPY dashboard/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY model.py .
COPY eda.py .
COPY dashboard/generate_dashboard.py generate_dashboard.py
COPY dashboard/run_dashboard.py run_dashboard.py

CMD python generate_dashboard.py && python run_dashboard.py