FROM python:3.11-slim


WORKDIR /usr/src/app

RUN apt-get update \
 && apt-get install -y curl \
 && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV NAME World

CMD ["python", "app.py"]